import { StyleSheet } from "react-native";

const styles = (color) =>
  StyleSheet.create({
    container: {
      height: "100%",
      width: "100%",
      position: "relative",
      display: "flex",
      justifyContent: "space-around",
    },
    centerBtn: {
      width: "100%",
      alignItems: "center",
      paddingBottom: 35,
      marginTop: 35,
    },
    pickColor: {
      marginLeft: 30,
    },
    submitBtn: {
      width: 150,
      height: 50,
      backgroundColor: color || "#6fbded",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 7,
    },
    submitBtn2: {
      width: 100,
      height: 50,
      backgroundColor: color || "#6fbded",
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 5,
    },
    horaBtnCont: {
      width: "80%",
      margin: 20,
      marginLeft: "10%",
      display: "flex",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    submitText: {
      fontSize: 20,
      fontWeight: "600",
      color: "white",
    },
    inline: {
      display: "flex",
      margin: 10,
      marginLeft: 5,
      flexDirection: "row",
    },
    contColor: {
      justifyContent: "center",
      position: "absolute",
      alignItems: "center",
      height: "100%",
      width: "100%",
      backgroundColor: "rgba(52, 52, 52, 0.8)",
    },
    titulo: {
      fontSize: 20,
      textAlign: "center",
      padding: 20,
      color: color || "#6fbded",
    },
    label: {
      fontSize: 18,
      fontWeight: "500",
      marginLeft: 20,
      color: color || "#6fbded",
    },
    label2: {
      fontSize: 18,
      fontWeight: "500",
      marginLeft: 20,
      marginTop: 12,
      marginBottom: 12,
      color: "black",
    },
    input: {
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderColor: "lightgrey",
      borderRadius: 5,
      height: "5%",
      margin: 10,
      marginLeft: 20,
      color: "black",
      fontSize: 18,
    },
    inputDesc: {
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderColor: "lightgrey",
      borderRadius: 5,
      height: "auto",
      margin: 10,
      marginLeft: 20,
      color: "black",
      fontSize: 16,
    },
    inputErr: {
      backgroundColor: "white",
      borderBottomWidth: 1,
      borderColor: "red",
      borderRadius: 5,
      height: "5%",
      margin: 10,
      color: "black",
      fontSize: 18,
    },
  });

export default styles;
